### ISSUE TITLE
Consider a global npm package?

### ISSUE THREAD

**Issue by rnkn** [ifrost/afterwriting-labs#29]
I love `awc.js`. I think it's the best CLI for generating PDFs from Fountain files.

I'd like to install as a global package but it appears `afterwriting-labs` is not set up for that. Ideally I'd like to be able to `npm install afterwriting` or similar.

**Comment by ifrost** [comment]
Thanks Paul! I've added afterwriting to the public npm registry. To install run:
`$ npm install afterwriting -g`
`$ afterwriting --help`

**Comment by rnkn** [comment]
Awesome thanks Piotr! This made my day.

Although I have encountered a problem calling `afterwriting`:
~~~sh
$ which env
/usr/bin/env
$ which node
/usr/local/bin/node
$ which afterwriting
/usr/local/bin/afterwriting
$ env node
> process.exit()
$ afterwriting --help
env: node\r: No such file or directory
$ afterwriting
env: node\r: No such file or directory
~~~
Might be a DOS encoding issue?

**Comment by ifrost** [comment]
Eww, sorry, it's because I work on Windows... I'll try to sort it out!

**Comment by ifrost** [comment]
Should be working now!

**Comment by rnkn** [comment]
I got the 1.2.6 version you pushed to npm, but I'm still getting the `env: node\r: No such file or directory` error. I'll try fiddle with replacing the line endings on my end to make sure that really is the issue.

**Comment by rnkn** [comment]
Boom! In Emacs, `M-x set-buffer-file-coding-system RET utf-8-unix RET` and it works. Brilliant work Piotr!

**Comment by ifrost** [comment]
Sweet! 

All Mac users will face the same issue, though. I fixed the line endings locally on Windows, but something fishy happened behind the scenes. If nothing helps, I'll have to buy a Mac :P

**Comment by rnkn** [comment]
This sounds like the issue: https://github.com/joyent/node/issues/4310#issuecomment-10717663

So it appears (I'm guessing here) that all *nix systems will run into the same problem.

But you say you converted to Unix-style line endings before republishing and npm still changed them back? That is definitely fishy.

**Comment by ifrost** [comment]
Weird. I tried on a Mac today and everything went smoothly with version 1.2.6.

**Comment by rnkn** [comment]
I'm pretty new to node so it's entirely possible I was still on 1.2.5. I will test thoroughly before posting again. Given you have a node global package working on OS X we can consider this specific issue closed.
